language: node_js
node_js: 10
script: yarn build
notifications:
  email: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: dist